"""
sk_visualize.py — SK Hynix prediction visualization (4 plots)
=============================================================
Requires sk_cv_predictions.parquet (generated by sk3_ablation.py).

Plots:
  sk_pred_vs_actual.png    — Actual vs Predicted time series
  sk_residuals.png         — Model A residual bar chart
  sk_bull_bear_scatter.png — Bull / Bear scatter (CV vs Hold-out)
  sk_rolling_diracc.png    — Rolling 12-month direction accuracy
"""

import os
import sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sk_config import SK_DATA_DIR, SK_FIG_DIR, SK_METRIC_DIR, TARGET_NAME

PRED_PATH      = os.path.join(SK_DATA_DIR,   "sk_cv_predictions.parquet")
CV_METRIC_PATH = os.path.join(SK_METRIC_DIR, "sk_ablation_results_v2.csv")
HO_METRIC_PATH = os.path.join(SK_METRIC_DIR, "sk_holdout_results.csv")

ROLL_WINDOW = 12
BAR_WIDTH   = 22          # days

C_TRUE  = "black"
C_A     = "#1565C0"       # deep blue
C_B     = "#E65100"       # deep orange
C_C     = "#2E7D32"       # deep green
C_POS   = "#EF5350"       # red (over-predict)
C_NEG   = "#42A5F5"       # blue (under-predict)
C_HO_BG = "#FFFDE7"       # light yellow
C_HO_VL = "#F9A825"       # amber


# ── helpers ──────────────────────────────────────────────────
def _fv(val, spec=".1f", suffix=""):
    try:
        if np.isnan(float(val)):
            return "N/A"
        return format(float(val), spec) + suffix
    except Exception:
        return "N/A"


def _holdout_bounds(df: pd.DataFrame):
    """Return (ho_start, all_end) as Timestamps from split column."""
    ho = df[df["split"] == "holdout"]
    if len(ho) == 0:
        return None, None
    return ho["date"].min(), df["date"].max()


def _add_holdout_bg(ax, ho_start, all_end, label: str = ""):
    """Amber vertical line + light-yellow background for hold-out region."""
    if ho_start is None:
        return
    ax.axvspan(ho_start, all_end, color=C_HO_BG, alpha=1.0, zorder=0,
               label=label if label else "_nolegend_")
    ax.axvline(ho_start, color=C_HO_VL, linewidth=1.2, linestyle="--", zorder=2)


def _add_holdout_label(ax, ho_start, y_frac: float = 0.96):
    if ho_start is None:
        return
    ymin, ymax = ax.get_ylim()
    ax.text(
        ho_start, ymin + (ymax - ymin) * y_frac,
        f"  Hold-out start ({ho_start.strftime('%Y-%m')})",
        color=C_HO_VL, fontsize=8.5, va="top", ha="left", zorder=6, clip_on=True,
    )


def _date_fmt(ax):
    ax.xaxis.set_major_locator(mdates.YearLocator(2))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
    plt.setp(ax.get_xticklabels(), rotation=0)


# ── data loading ─────────────────────────────────────────────
def load_preds() -> pd.DataFrame:
    if not os.path.exists(PRED_PATH):
        raise FileNotFoundError(
            f"Prediction file not found:\n  {PRED_PATH}\n"
            "Run: python skhynix/sk3_ablation.py"
        )
    df = pd.read_parquet(PRED_PATH)
    df["date"] = pd.to_datetime(df["date"])
    return df.sort_values("date").reset_index(drop=True)


def load_metrics():
    """Return (cv_m, ho_m) dicts keyed by model string ('A','B','C')."""
    def _load(path):
        if not os.path.exists(path):
            return {}
        tmp = pd.read_csv(path)
        return {str(row["model"]): row.to_dict() for _, row in tmp.iterrows()}
    return _load(CV_METRIC_PATH), _load(HO_METRIC_PATH)


# ── Plot 1: Actual vs Predicted time series ───────────────────
def plot_pred_vs_actual(df: pd.DataFrame, cv_m: dict, ho_m: dict):
    fig, ax = plt.subplots(figsize=(16, 5))

    ho_start, all_end = _holdout_bounds(df)
    _add_holdout_bg(ax, ho_start, all_end)

    # y = 0 baseline
    ax.axhline(0, color="#9E9E9E", linewidth=0.8, linestyle="--", zorder=1)

    # Legend labels with CV metrics
    rmse_a = cv_m.get("A", {}).get("rmse",    float("nan"))
    dacc_a = cv_m.get("A", {}).get("dir_acc", float("nan"))
    rmse_b = cv_m.get("B", {}).get("rmse",    float("nan"))
    dacc_b = cv_m.get("B", {}).get("dir_acc", float("nan"))

    lbl_a = f"Model A — Full  [CV RMSE={_fv(rmse_a)}, DirAcc={_fv(dacc_a)}%]"
    lbl_b = f"Model B — No supply  [CV RMSE={_fv(rmse_b)}, DirAcc={_fv(dacc_b)}%]"

    ax.plot(df["date"], df["y_true"],   color=C_TRUE, linewidth=1.5, label="Actual (y_true)", zorder=4)
    ax.plot(df["date"], df["y_pred_A"], color=C_A,    linewidth=1.2, label=lbl_a,              zorder=4)
    ax.plot(df["date"], df["y_pred_B"], color=C_B,    linewidth=1.0, linestyle="--",
            label=lbl_b, zorder=4)

    _add_holdout_label(ax, ho_start)
    _date_fmt(ax)

    ax.set_xlabel("Date")
    ax.set_ylabel("6-Month Forward Return (%)")
    ax.set_title(f"SK Hynix — Predicted vs Actual  [{TARGET_NAME}]")
    ax.legend(loc="upper left", fontsize=8.5, framealpha=0.88)
    plt.tight_layout()

    path = os.path.join(SK_FIG_DIR, "sk_pred_vs_actual.png")
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  → {path}")


# ── Plot 2: Residuals bar chart ───────────────────────────────
def plot_residuals(df: pd.DataFrame):
    residuals = (df["y_pred_A"] - df["y_true"]).values
    dates_num = mdates.date2num(df["date"].tolist())   # float days for bar width

    fig, ax = plt.subplots(figsize=(16, 4))

    ho_start, all_end = _holdout_bounds(df)
    _add_holdout_bg(ax, ho_start, all_end)
    ax.axhline(0, color="black", linewidth=0.9, zorder=3)

    # Colour-coded bars: red = over-predict, blue = under-predict
    pos = residuals >= 0
    neg = ~pos
    ax.bar(dates_num[pos], residuals[pos],  width=BAR_WIDTH, color=C_POS, alpha=0.80,
           label="Over-predict  (pred > actual)", zorder=2)
    ax.bar(dates_num[neg], residuals[neg],  width=BAR_WIDTH, color=C_NEG, alpha=0.80,
           label="Under-predict  (pred < actual)", zorder=2)
    ax.xaxis_date()

    # Hold-out mean residual — horizontal dotted line in hold-out region only
    ho_mask = df["split"].values == "holdout"
    if ho_mask.any():
        ho_res  = residuals[ho_mask]
        ho_nums = dates_num[ho_mask]
        ho_mean = float(np.mean(ho_res))
        ax.hlines(ho_mean, ho_nums.min(), ho_nums.max(),
                  colors=C_HO_VL, linewidth=1.5, linestyle=":",
                  label=f"Hold-out mean residual: {ho_mean:+.1f}%", zorder=5)
        # Text annotation
        ymin, ymax = ax.get_ylim()
        ax.text(mdates.num2date(ho_nums.min()),
                ho_mean + (ymax - ymin) * 0.03,
                f"  mean: {ho_mean:+.1f}%",
                color=C_HO_VL, fontsize=8, va="bottom", ha="left", zorder=6)

    _add_holdout_label(ax, ho_start, y_frac=0.93)
    _date_fmt(ax)

    ax.set_xlabel("Date")
    ax.set_ylabel("Residual  (pred − actual, %)")
    ax.set_title("SK Hynix — Model A Residuals")
    ax.legend(loc="upper left", fontsize=8.5, framealpha=0.88)
    plt.tight_layout()

    path = os.path.join(SK_FIG_DIR, "sk_residuals.png")
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  → {path}")


# ── Plot 3: Bull / Bear scatter ───────────────────────────────
def plot_bull_bear_scatter(df: pd.DataFrame):
    df_cv = df[df["split"] == "cv"].copy()
    df_ho = df[df["split"] == "holdout"].copy()

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    specs = [
        ("Bull  (actual > 0)",  df_cv["y_true"] > 0,  df_ho["y_true"] > 0),
        ("Bear  (actual <= 0)", df_cv["y_true"] <= 0, df_ho["y_true"] <= 0),
    ]

    for ax, (period_lbl, mask_cv, mask_ho) in zip(axes, specs):
        sub_cv = df_cv[mask_cv]
        sub_ho = df_ho[mask_ho]

        def _dacc(y_t, y_p):
            if len(y_t) == 0:
                return float("nan")
            return float(np.mean((y_p > 0) == (y_t > 0)) * 100)

        da_cv = _dacc(sub_cv["y_true"].values, sub_cv["y_pred_A"].values)
        da_ho = _dacc(sub_ho["y_true"].values, sub_ho["y_pred_A"].values)

        # CV: blue circles (small, semi-transparent)
        if len(sub_cv):
            ax.scatter(sub_cv["y_true"], sub_cv["y_pred_A"],
                       color=C_A, alpha=0.50, s=35,
                       label=f"CV  (n={len(sub_cv)})", zorder=3)
        # Hold-out: red circles (larger, more opaque)
        if len(sub_ho):
            ax.scatter(sub_ho["y_true"], sub_ho["y_pred_A"],
                       color=C_POS, alpha=0.80, s=90,
                       label=f"Hold-out  (n={len(sub_ho)})", zorder=4)

        # y = x perfect-prediction diagonal
        combined = pd.concat([
            sub_cv["y_true"], sub_ho["y_true"],
            sub_cv["y_pred_A"], sub_ho["y_pred_A"],
        ])
        if len(combined):
            pad  = max(abs(combined.min()), abs(combined.max())) * 0.10
            vmin = combined.min() - pad
            vmax = combined.max() + pad
            ax.plot([vmin, vmax], [vmin, vmax],
                    color="#9E9E9E", linewidth=0.9, linestyle="--",
                    label="Perfect prediction  (y = x)", zorder=2)
            ax.set_xlim(vmin, vmax)
            ax.set_ylim(vmin, vmax)

        ax.axhline(0, color="#BDBDBD", linewidth=0.5, linestyle=":")
        ax.axvline(0, color="#BDBDBD", linewidth=0.5, linestyle=":")

        cv_str = f"CV: {_fv(da_cv)}%"
        ho_str = f"Hold-out: {_fv(da_ho)}%"
        ax.set_title(f"{period_lbl}\nDir Acc — {cv_str},  {ho_str}", fontsize=10)
        ax.set_xlabel("Actual 6M Return (%)")
        ax.set_ylabel("Predicted 6M Return (%)")
        ax.legend(fontsize=8.5, framealpha=0.88)

    plt.suptitle("SK Hynix — Bull / Bear Scatter  [Model A]", fontsize=12)
    plt.tight_layout()

    path = os.path.join(SK_FIG_DIR, "sk_bull_bear_scatter.png")
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  → {path}")


# ── Plot 4: Rolling direction accuracy ───────────────────────
def plot_rolling_diracc(df: pd.DataFrame, window: int = ROLL_WINDOW):
    fig, ax = plt.subplots(figsize=(14, 4))

    ho_start, all_end = _holdout_bounds(df)
    _add_holdout_bg(ax, ho_start, all_end, label="Hold-out period")

    # Reference baselines
    ax.axhline(50, color="#9E9E9E", linewidth=1.0, zorder=1, label="Random baseline (50%)")
    ax.axhline(70, color="#9E9E9E", linewidth=1.0, linestyle="--", zorder=1,
               label="Practical threshold (70%)")

    # Three model lines
    model_cfg = [
        ("A", C_A,  "-",  1.6, "Model A  (Full)"),
        ("B", C_B,  "--", 1.1, "Model B  (No supply)"),
        ("C", C_C,  ":",  1.1, "Model C  (Supply only)"),
    ]
    for mk, color, ls, lw, label in model_cfg:
        correct = ((df["y_true"] > 0) == (df[f"y_pred_{mk}"] > 0)).astype(float) * 100
        rolling = correct.rolling(window, min_periods=window).mean()
        ax.plot(df["date"], rolling,
                color=color, linewidth=lw, linestyle=ls,
                label=f"{label}  [rolling {window}m]", zorder=3)

    _add_holdout_label(ax, ho_start, y_frac=0.97)
    _date_fmt(ax)

    ax.set_ylim(0, 110)
    ax.set_xlabel("Date")
    ax.set_ylabel(f"Rolling {window}-Month Dir Acc (%)")
    ax.set_title(f"SK Hynix — Rolling {window}-Month Direction Accuracy")
    ax.legend(loc="lower right", fontsize=8.5, framealpha=0.88)
    plt.tight_layout()

    path = os.path.join(SK_FIG_DIR, "sk_rolling_diracc.png")
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  → {path}")


# ── main ─────────────────────────────────────────────────────
def main():
    print("=" * 56)
    print("  SK Hynix Prediction Visualization  (4 plots)")
    print("=" * 56)

    print("\n[1] Loading predictions ...")
    df = load_preds()
    df_cv = df[df["split"] == "cv"]
    df_ho = df[df["split"] == "holdout"]
    print(f"  CV       : {len(df_cv)} rows  "
          f"{df_cv['date'].min().strftime('%Y-%m')} ~ {df_cv['date'].max().strftime('%Y-%m')}")
    print(f"  Hold-out : {len(df_ho)} rows  "
          f"{df_ho['date'].min().strftime('%Y-%m')} ~ {df_ho['date'].max().strftime('%Y-%m')}")

    print("\n[2] Loading metrics ...")
    cv_m, ho_m = load_metrics()
    for mk in ["A", "B", "C"]:
        r  = _fv(cv_m.get(mk, {}).get("rmse",    float("nan")))
        da = _fv(cv_m.get(mk, {}).get("dir_acc", float("nan")))
        print(f"  Model {mk} (CV)  RMSE={r},  DirAcc={da}%")

    print("\n[3] Generating plots ...")
    plot_pred_vs_actual(df, cv_m, ho_m)
    plot_residuals(df)
    plot_bull_bear_scatter(df)
    plot_rolling_diracc(df)

    print("\n  Done.")


if __name__ == "__main__":
    main()
